# Generated by Django 2.1.1 on 2018-09-17 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.CharField(default='null', max_length=255)),
                ('spotifyID', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.CharField(default='null', max_length=255)),
                ('spotifyID', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('passKey', models.CharField(max_length=255, null=True)),
                ('location', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('spotifyID', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotifyID', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserExt',
            fields=[
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('firstName', models.CharField(blank=True, max_length=127, null=True)),
                ('lastName', models.CharField(blank=True, max_length=127, null=True)),
                ('spotifyID', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='playlist',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='api.UserExt'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(blank=True, null=True, to='api.Song'),
        ),
        migrations.AddField(
            model_name='party',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UserExt'),
        ),
        migrations.AddField(
            model_name='party',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='parties', to='api.UserExt'),
        ),
        migrations.AddField(
            model_name='party',
            name='queue',
            field=models.ManyToManyField(blank=True, null=True, related_name='partyQueueSongs', to='api.Song'),
        ),
        migrations.AddField(
            model_name='party',
            name='stream',
            field=models.ManyToManyField(blank=True, null=True, related_name='partyStreamSongs', to='api.Song'),
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='api.Artist'),
        ),
    ]
