# Generated by Django 2.1.1 on 2018-09-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='song',
            name='dateAdded',
        ),
        migrations.RemoveField(
            model_name='song',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='song',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='song',
            name='title',
        ),
        migrations.RemoveField(
            model_name='song',
            name='upvotes',
        ),
        migrations.RemoveField(
            model_name='userext',
            name='id',
        ),
        migrations.RemoveField(
            model_name='userext',
            name='user',
        ),
        migrations.AddField(
            model_name='userext',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='queue',
            field=models.ManyToManyField(blank=True, null=True, related_name='partyQueueSongs', to='api.Song'),
        ),
        migrations.AlterField(
            model_name='party',
            name='stream',
            field=models.ManyToManyField(blank=True, null=True, related_name='partyStreamSongs', to='api.Song'),
        ),
        migrations.AlterField(
            model_name='userext',
            name='spotifyID',
            field=models.CharField(default='null', max_length=255, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
